### ISSUE TITLE
openai_utils.py 기능 수정

### ISSUE THREAD

**Issue by hwarang97** [f-lab-edu/please-just-texting#12]
## 문제 상황 
- 프롬프트에 대한 일정 정보가 여러개 출력

`[ { "date": "2023-07-17", "title": "전역 모임", "description": "전역하면 함 봐야죵" }, { "date": "2023-07-21", "title": "전역 모임", "description": "전역하면 함 봐야져" }, { "date": "2023-07-22", "title": "가족 여행", "description": "전 22일부터 가족끼리 여행이라…" }, { "date": "2023-07-23", "title": "전역 모임", "description": "전역주는 안되고 담주는 삽가넝이요~" }, { "date": "2023-07-17", "title": "가능한 날짜 토론", "description": "톡게시판 '투표': 가능한 날짜" }, { "date": "2023-07-07", "title": "가능한 날짜 토론", "description": "톡게시판 '글 공유': 가능한 날짜" }, { "date": "2023-07-08", "title": "가능한 날짜 토론", "description": "톡게시판 '투표 종료': 가능한 날짜." }, { "date": "2023-07-12", "title": "장소 정하기", "description": "좋은 생각 있으신가요??" } ]`

## 목적
- 프롬프트에 대한 일정 정보가 하나만 출력되도록 코드 수정

## 수정 적용 대상
- openai_utils.py
- main.py

## 할 일
- [x] 문제의 원인 파악
- [x] openai_utils 출력 일정 정보 하나만 되도록 변경
- [x] main 에서 수정할 부분이 없는지 확인

**Comment by hwarang97** [comment]
관련된 모든 사항들을 fix/openai_tuils-issue 에서 진행하였습니다.
문제가 되었던 사항들을 전부 해결하고 마무리지었습니다.

**Comment by FlabKenneth** [comment]
양식 잡으실 때 큰 것 -> 작은 것 순으로 두괄식으로 표현해주시면 좋습니다.
예를들어 위 양식은 목적 -> 상황 -> 수정 파일 -> 할 일 순으로 작성주시면 좋을 것 같네요 ㅎㅎ

그리고 마이너하지만 JSON은 beautifier 걸고 나서 block snippet 형태로 잡아주시면 읽는 분들에게 좋습니다!

```json
[
    {
        "date": "2023-07-17",
        "title": "전역 모임",
        "description": "전역하면 함 봐야죵"
    },
    {
        "date": "2023-07-21",
        "title": "전역 모임",
        "description": "전역하면 함 봐야져"
    },
    {
        "date": "2023-07-22",
        "title": "가족 여행",
        "description": "전 22일부터 가족끼리 여행이라…"
    },
    {
        "date": "2023-07-23",
        "title": "전역 모임",
        "description": "전역주는 안되고 담주는 삽가넝이요~"
    },
    {
        "date": "2023-07-17",
        "title": "가능한 날짜 토론",
        "description": "톡게시판 '투표': 가능한 날짜"
    },
    {
        "date": "2023-07-07",
        "title": "가능한 날짜 토론",
        "description": "톡게시판 '글 공유': 가능한 날짜"
    },
    {
        "date": "2023-07-08",
        "title": "가능한 날짜 토론",
        "description": "톡게시판 '투표 종료': 가능한 날짜."
    },
    {
        "date": "2023-07-12",
        "title": "장소 정하기",
        "description": "좋은 생각 있으신가요??"
    }
]
```

이렇게요!

**Comment by hwarang97** [comment]
감사합니다. 적용해서 수정하겠습니다.
