### ISSUE TITLE
BUG: 구글 OAuth2 인증 문제

### ISSUE THREAD

**Issue by hwarang97** [f-lab-edu/please-just-texting#36]
## 상황

구글 캘린더 클라이언트가 삭제되었다는 에러 로그 발생했습니다. 로직이 정상 작동하지 않아, token 파일을 발급받지 못해 생긴 문제로 보입니다.

### 로직

```python
def get_calendar_service() -> Request:
    creds = None

    token_path = PROJECT_ROOT / "token.pickle"
    if os.path.exists(token_path):
        with open(token_path, "rb") as token:
            creds = pickle.load(token)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file("credentials.json", SCOPES)
            creds = flow.run_local_server(port=0)

        with open("token.pickle", "wb") as token:
            pickle.dump(creds, token)

    service = build("calendar", "v3", credentials=creds)
    return service
```

<token.pickle이 존재할 시>
1. token.pickle 사용
2. 만료되었으면, token.pickle 갱신 이후 사용

<token.pickle이 없을 시>
1. 로컬의 credentials.json 파일을 활용해, token.pickle 발급 후 사용

유효하지 않은 token.pickle이 로컬에 남아있어 새로운 token을 발급받지 못해
인증에 실패하는것으로 보입니다. 따라서 token.pickle이 없을 경우의 로직을 이용해 해결하면 되지만, 해당 로직이 정상적으로 작동하지 않습니다. 

<에러 로그>
- webbrowser.Error: could not locate runnable browser

creds = flow.run_local_server(port=0) 작동과정에서 도커 컨테이너는 브라우저를 이용하지 못하기에 발생하는 문제로 보입니다.

## 목적

~구글 OAuth2 인증에 필요한 token을 정상 발급받을 수 있도록 수정합니다.~
GCP(Google Cloud Plaform)에서 Service Account를 생성한 뒤, 이를 활용하여 인증 문제를 해결한다.

## 작업 대상
calender_utils.py 의 "get_calendar_service" 함수

## 할일
- [x] 도커 환경에 맞는 인증 방식으로 변경
- [x] 기존에는 어떻게 token을 발급받았는지 확인

## 결과

- Service Account에서 제공하는, domain-wide delegation을 이용해 애플리케이션 내에서 접근 허가를 받지 않으면서 인증을 처리할 수 있게 되었습니다. 
- 기존에는 로컬에서 웹 브라우저로 인증을 거쳐 token을 발급받은 후, 도커로 실행할 때 사용하는 방법으로 진행했습니다.

**Comment by KennethanCeyer** [comment]
네 석제님 말씀처럼 creds를 가져오는 쪽에서
Chrome Browser Driver로 OAuth 2.0 flow를 실행시켜 Login을 하려고 할 때 에러가 난 것 같네요.

가장 Work around 형태로 fix한다면 Headless Chrome Browser Driver를 Ubuntu Docker Container상 설치해서,
그쪽 드라이버로 잡아주면 Flow 진행 상 문제가 없을 겁니다.

근데 애초에 해당 설계에서 OAuth Flow를 사용자 Creds로 부터 받아올 필요 없이 (이건 G Suite Feature 같은데 이걸 쓸 이유가 없어보이네요 )
Google Cloud의 Service Account Key를 JSON 형태로 다운받으셔서,
[Google Calendar API by using Service Account](https://medium.com/iceapple-tech-talks/integration-with-google-calendar-api-using-service-account-1471e6e102c8)로 사용하시는게 맞아보이네요.

이렇게 판단한 이유는 다음과 같습니다.
1. 사용자 Google ID를 접근 허용 받아 직접 제어할 이유가 없으므로. (즉 OAuth로 사용자 Scope를 얻어내는 flow 과정 불필요)
2. 지정한 Service Account에서 사용자 gmail address에 "캘린더를 초대" 하는 형태가 더 간단하고 관리가 용이함.
3. OAuth 2.0은 특성상 사용자 토큰 만료시 재갱신이 필요하나, Permanant한 Auth 방식은 보안에 심각한 결함이 초래됨.
   3-1. 따라서 OAuth 2.0을 제대로 사용할 것이라면, 프론트엔드 웹을 구성하고 OAuth를 주기적으로 갱신할 수 있도록 해야하나 F-Lab 프로젝트 특성상 이 부분까지 프로젝트 기간내 구현이 어려움.

**Comment by hwarang97** [comment]
인증 방법을 완전히 대체하였습니다.
